### ISSUE TITLE
Enable/disable language assistance

### ISSUE THREAD

**Issue by pchalamet** [tomasr/viasfora#100]
I find Viasfora useful for F# but not for C#... and I can't find a way to disable Viasfora for specific language in options. 

Having the option to choose "assisted" languages would be great (for classifier, rainbow, delimiter..).
Thanks.

**Comment by tomasr** [comment]
That's actually a very interesting suggestion.... I'm curious what you'd consider "enable/disable" per language.... every single viasfora feature? Or just a specific subset of them?

Also would love to know what you don't find useful in C#, or if there is something that is missing that causes it :)

**Comment by pchalamet** [comment]
I just need to enable/disable text editor related stuff per language (well, that stuff under the "General" category).

Why I do not like Viasfora for C# is that I'm just happy with my R# color scheme since years. And C# has far more syntax sugar so highlighting can be more visible if one need it (and mostly well supported with R#).

**Comment by tomasr** [comment]
Makes sense, I'll definitely implement this!

Probably won't get around to it for a while, though, as I've got 2 whole weeks of business travel ahead, but I promise it will be in as soon as I can :)

**Comment by pchalamet** [comment]
Thanks a lot Tomas !

- Pierre

**Comment by tomasr** [comment]
I've now done the bulk of the work to implement this. This will allow you to control all rainbow-related features, as well as keyword highlighting per-language, though not the rest (I'm not sure it makes sense for any other features).

Implementation isn't quite complete yet, because some languages don't have options screens at this point, so there's no way in the Options dialog to enable/disable it for them. For example, you can disable for CSS right now, but won't be able to do so for LESS or SASS.

Need to figure out a better way of exposing it for those ones.

You can find a dev build here: https://ci.appveyor.com/project/tomasr/viasfora/build/artifacts

Let me know if that works for you :)

**Comment by pchalamet** [comment]
It works great - at least for C# & F#. Thanks Tomas.
