### ISSUE TITLE
Some ideas to share, Not an issue per se.

### ISSUE THREAD

**Issue by hlide** [tomasr/viasfora#105]
First of all, thanks for this amazing extension!

I had some couple of ideas - while I am not sure they could be of interest or easily implementable and fast enough to be rendered - that I would like to share to extend your extension with some missing features I would like to see - hoping I am not the only one to wish them.

1) colors of nested blocks (brackets, parenthesis, etc.). While rainbow colors can be helpful to distinguish nested ones, their choices of colors are a little bit too much to my taste. I would have rather consider some gradient colors instead, with the ability to choose the gradient color points.

2) instead of only playing on colors, can extension play on font size for the open and close symbols as we usually do with mathematical expression? I guess it is a difficult one, because editor uses fixed size fonts and those symbols could be awkward to render if they are not in the same line. Point (4) is about how to render those symbols in a multi-line block.

3) while not coloring the bounding box of a block having the matched open and close symbols, using the gradient colors as exposed in point (1)? 

4) Not sure if it can be implemented and about the given result. Blocks can be rendered as a bounding box with having the open symbol covering all the left side and the close symbol covering all the right side as usually done in complex mathematical expression.

**Comment by tomasr** [comment]
These are good suggestions, thanks for that! Let me discuss them.

1) I've thought about this, and it's something I'd like to add, but don't want to have to end up duplicating too much code to support this. How are you considering the gradient color points to be customizable? How would that look? Notice that nothing prevents you from just customizing the existing colors to suit your preferences right now!

2) That could potentially be doable, but honestly, it would just look ugly (it would play havoc with the usual line height and be a mess).

3) Not quire sure what you mean by this one. Can you elaborate further?

4) That would be hard. Mostly because remember the extension deals with more than one kind of brace. I guess you're thinking mostly of strictly {} braces? What happens in, say, a lambda expression containing {} with parentheses right before and after? How would that look?

**Comment by pnacht** [comment]
Making use of this "issue" for another suggestion:

Would it be possible to separate the counters for the different brace-types? For example, the following code currently displays brackets `[]` with different colors since they are in different scopes.

    int a[4]; // color 1
    if(true)
        int b[4]; //color 2 

Could they be displayed with the same color, since they are in the same (to make up a term) "bracket-scope" (both are the first brackets in their operation)? Meanwhile, something like `a[b[2]]` would display  different colors for the different bracket-pairs. To use your example of lambda-expressions above, this would cause the braces and brackets to have the same color. To my mind that is entirely fine, but I understand if this would be considered a problem. The solution would then be to allow for different color schemes for brackets, braces and parentheses, but that seems excessive.

**Comment by tomasr** [comment]
@pnacht I'm not quite sure what you mean.... color is assigned based on nesting depth; in your example, there is no nesting and so all 3 lines would have braces in the same color (unless markup swallowed something in your example).

**Comment by pnacht** [comment]
Yeah, I forgot to put the braces for the `if`.

**Comment by tomasr** [comment]
@pnacht You don't mention what language this would be in.... C? C++? Every language has different syntax rules for this stuff, and so it would be really hard to implement (and in most languages this wouldn't even be considered the same lexical scope.

I guess what you really want would be separate colors for each brace and that might actually be doable, but it wouldn't necessarily guarantee different colors (depends on how you'd set them up).

I've considered enabling that as an option, but it would be fairly ugly from a configuration point of view to support both....

**Comment by hlide** [comment]
sorry for the time to answer.

3) I think I mean each blocks has a bounding box with a gradient color as background

4) yeah I concur it will be difficult as it also means some kind self-formatting blocks to fit well.

Having both 3) and 4) would be doing like [blockly](https://code.google.com/p/blockly/) in the end - which is probably beyond the purpose of Viasfora, anyway.

**Comment by pnacht** [comment]
I am thinking in the "C languages" (C, C++, C#). In the example I gave, `a[2]` and `b[2]` are meant to be in different lexical scopes. My suggestion would be to disconsider lexical scopes and instead look at... "bracket/parenthesis/braces scope" (to make up a term again) within each statement. So, for each statement, independently of scope, the first level of brackets will have color A, the second level of brackets will have color B, etc. Likewise, the first level of parentheses will have color A, the second, B, etc. Likewise for braces. This way, two identical statements in different scopes will have identical coloring.

Here's an example (written in Word):
![image](https://cloud.githubusercontent.com/assets/15221358/11159057/9150564a-8a43-11e5-9ae9-e301eb93c965.png)
And an explanation:
![image](https://cloud.githubusercontent.com/assets/15221358/11159068/ad7e7388-8a43-11e5-9277-62d548192142.png)

Note the identical coloring of the declarations of `a` and `c`, which are identical other than scope.

I really enjoy this extension as-is, but I personally (you may very well disagree) find that knowing that a red (in this case) bracket will always represent the first bracket-level within a given statement to be a helpful bit of information. As-is, you can't know simply from the color of a bracket/brace/parenthesis what level it represents, since the level-1 color for the statement depends on its scope.

**Comment by tomasr** [comment]
@pnacht Thanks for the great explanation. I agree it would be useful, but I'd like to get rid of the terms "scope" and "statement" here.

What you are basically asking (in the only meaningful way I could do it) is simply to match the color to the brace based using separate nesting stacks for [], () and {}.

In your example, you're assuming that the color palette for all is the same, and that sort of works for your specific scenario, but it doesn't work for all languages (think, for example, Json where stuff such as [{}] is common.

I will think a bit about how to implement this. Part of it is easy, but part of it also requires some deep changes to how certain things work :)
