### ISSUE TITLE
Zoom in the Pick Definition window is not synchronized with zoom in editor until I zoom-in in the Pick Definition window 

### ISSUE THREAD

**Issue by xperiandri** [tomasr/viasfora#107]
Because of Viasfora zoom in the Pick Definition window is not synchronized with zoom in editor until I zoom-in in the Pick Definition window 

See bug report on Connect:
https://connect.microsoft.com/VisualStudio/feedback/details/1534777/zoom-in-the-pick-definition-window-is-not-synchronized-with-zoom-in-editor-until-i-zoom-in-in-the-pick-definition-window

See attached screenshots on Connect also.

**Comment by tomasr** [comment]
Thanks for the bug report. Is this VS2013 or VS2015?

Also, just to make sure I understand, you seem to be saying that if you zoom an editor window to > 100%, and then use Peek Definition, the pick definition embedded window opens up with 100% zoom instead of matching the zoom level of the original window.

Is that right? If so, I've reproduced it, and indeed it does not happen with Viasfora disabled. I'll take a look and see what is going on!

Thanks for the report!

**Comment by xperiandri** [comment]
2015 definitely
2013 maybe, it doesn't work on my PC now so I can't check

**Comment by xperiandri** [comment]
You understood me absolutely right
