### ISSUE TITLE
Increase font size of Environment and IntelliSense in Presentation Mode

### ISSUE THREAD

**Issue by xperiandri** [tomasr/viasfora#111]
Could you also increase font size in Presentation Mode for:
* Environment
* Member List
<img src="https://i-msdn.sec.s-msft.com/en-us/library/hcw1s69b.vs2015_Intellisense(v=vs.140).png?f=255&MSPPError=-2147217396"/>
* Parameter Info
<img src="https://i-msdn.sec.s-msft.com/en-us/library/hcw1s69b.VS2015_param_Info(v=vs.140).png?f=255&MSPPError=-2147217396"/>
* Quick Info
<img src="https://i-msdn.sec.s-msft.com/en-us/library/hcw1s69b.VS2015_Quick_info(v=vs.140).png?f=255&MSPPError=-2147217396"/>

**Comment by tomasr** [comment]
I've been looking at a way to implement this, as well as increase the environment font while at it.

However, it's not entirely simpler. I know how to go around it, but there are a *lot* of different possible fonts in VS that could need changing.

The other problem is default vs non-default font. For example, the environment font is set to Automatic, by default, which just means that the category doesn't exist at all. Meaning that to disable presentation mode I'd need to remove the category instead of simply changing the font size (otherwise it wound't quite be the same).

Also, another problem is ensuring that I can return things to the original settings if you decide to quit Visual Studio with Presentation Mode enabled. This is my biggest worry, and don't have a good solution for it yet.

**Comment by tomasr** [comment]
OK, I currently have code implemented that will increase the font size for the following categories:

* Environment Font
* Statement Completion
* Editor ToolTip

While the code works OK, I'm concerned about two things:

1) Changes are global. Since this involves modifying registry keys, it could affect multiple visual studio instances
2) I have no way to undo the changes to the environment if Visual Studio terminates in an unexpected manner (that is, it crashes).

The second one is what concerns me the most. The user could undo changes manually, but it would be annoying, at least.

**Comment by xperiandri** [comment]
Looks like Productivity Power Tools do the same.
