### ISSUE TITLE
Referencing the * operator in F# breaks colorizer

### ISSUE THREAD

**Issue by marklam** [tomasr/viasfora#116]
In the following source:
```
module Test 

let rainbowOk = ( 3 * (2 + 7 ))

let multiplyOperator_LooksLikeComment = (*)

let rainbowBroken = multiplyOperator_LooksLikeComment 3 (2 + 7)

```
The colorizer seems to get broken by the ```(*``` when referencing the function that multiplies two things together.

**Comment by tomasr** [comment]
Thanks for the report, @marklam!

This one is not quite as easy to fix, because I can't see any way to figure out the right meaning of `(*` here without knowledge of the syntax context in which it is used (unfortunately, I only do basic lexing with a few hacks to get around that).

Best I can probably do on the short term is just specifically ignore `(*)`, but that wouldn't help if the code looked liked `(* )` (i.e just one extra space would break that hack).

**Comment by tomasr** [comment]
On second look, sounds like `(* )` is actually recognized as an open comment, so this would not be an issue. Can you give the dev build at https://ci.appveyor.com/project/tomasr/viasfora/ a try?

**Comment by marklam** [comment]
Yes, that fixes it. 
According to the docs, it's legal to define other operators that begin with a ```*```, followed with a sequence of other operator characters - but I can't define or reference functions with those names without putting a space inside the parentheses - so I guess the compiler has a special case for ```(*)``` too.
Thanks very much for the fix!
