### ISSUE TITLE
VS 2017 Performance Issues

### ISSUE THREAD

**Issue by RandyBuchholz** [tomasr/viasfora#180]
Viasfora gets flagged by VS2017 RC as having performance issues, which it does.  VS often goes into a  "Not Responding" mode and prevents typing. With Viasfora installed this lasts several seconds longer. 

Absolutely love this extension!

**Comment by tomasr** [comment]
Thanks for the info, @RandyBuchholz.

I've implemented some changes already to minimize the impact on VS2017 on the dev branch, but I have not seen any not responding events. Would you be open to helping me troubleshoot that further?

**Comment by RandyBuchholz** [comment]
Glad to help. Let me know if there is anything specific you want me to look at.

**Comment by tomasr** [comment]
Any chance you could capture and share a memory dump of devenv.exe when the hang happens? (`procdump.exe -h` works well for this)

Or else, capture a PerfView trace when reproducing the issue and then sharing the resulting PerfView.etl.zip file. Either one of those would be awesome (if you need help doing these let me know)

**Comment by RandyBuchholz** [comment]
I haven't used those tools before. Let me spend a little time getting familiar with them and then I'll come back to you for more details.

**Comment by tomasr** [comment]
Thanks! If you want to setup a call/hangout/skype whatever session to do it, let me  know; happy to assist :smile:. I do appreciate *a lot* all the help finding out any issues!

**Comment by tomasr** [comment]
More investigation on this for v3.5 besides changes already done.

**Comment by Donaldpherman** [comment]
I get the same error on 4.2.188.  Should I open a new issue?
![image](https://user-images.githubusercontent.com/3155787/61406500-d3949d80-a890-11e9-9268-9e9a2cbde611.png)

**Comment by tomasr** [comment]
@Donaldpherman What VS version? Also, do you have any other extensions installed?

**Comment by Donaldpherman** [comment]
Microsoft Visual Studio Professional 2017 
Version 15.9.13
VisualStudio.15.Release/15.9.13+28307.718
Microsoft .NET Framework
Version 4.8.03761

Installed Version: Professional

Visual C++ 2017   00370-20008-88648-AA225
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.14.20131.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   15.8.31590
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.61435.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Customize Visual Studio Window Title   4.0
This lightweight extension allows changing the window title of Visual Studio to include a folder tree with a configurable min depth and max depth distance from the solution/project file, and the use of special tags to help with many other possible scenarios (Git, Hg, TFS, SVN...). 
Solution-specific overriding rules are available as well to cover virtually any possible renaming needs. It can also be configured so that the rules apply only when at least two instances of Visual Studio are running with the same window title.
This is particularly useful when branching a solution/project: it becomes possible to easily identify which branch you are working on, in case both would have the same solution/project name.

Find Changeset By Comment   1.0
This extension is used to find changesets that contains a specific comment.

IncludeToolbox Extension   0.2
Tools around C/C++ #includes

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0
MLGen Package Visual Studio Extension Detailed Info

Multiline Search and Replace   2.3
Adds multiline search and replace functionality to Visual Studio.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Office Developer Tools for Visual Studio 2017 ENU   15.0.28224.00
Microsoft Office Developer Tools for Visual Studio 2017 ENU

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

RunPowerShellCommand Extension   1.0
RunPowerShellCommand Visual Studio Extension Detailed Info

Smart Command Line Arguments Extension   2.1.2
A Visual Studio Extension which aims to provide a better UI to manage your command line arguments. For additional information, visit https://github.com/MBulli/SmartCommandlineArgs

SmartPaster2013   1.0
Paste clipboard into comments or string builder

SQL Server Data Tools   15.1.61906.03120
Microsoft SQL Server Data Tools

StopOnFirstBuildError   1.0
StopOnFirstBuildError

Stops a solution build immediately after a project has failed to build.

http://tech.einaregilsson.com/2011/01/06/stop-build-on-first-error-in-visual-studio-2010/

Sugoi LocalHistory   1.0
Sugoi LocalHistory

TypeScript Tools   15.9.30524.2002
TypeScript Tools for Microsoft Visual Studio

Viasfora   4.2.188
Add color to your Visual Studio editor!

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ Error Fixes Extension   1.0
Visual C++ Error Fixes

Visual Commander   3.1.1
For more information about Visual Commander, see the website at https://vlasovstudio.com/visual-commander/.

Visual F# Tools 10.2 for F# 4.5   15.8.0.0.  Commit Hash: 6e26c5bacc8c4201e962f5bdde0a177f82f88691.
Microsoft Visual F# Tools 10.2 for F# 4.5

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Spell Check Everywhere   VSSpellCheckEverywhere
An extension that enables spell checking within any Visual Studio file editor or tool window that uses WPF text boxes.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Spell Checker   VSSpellChecker
An editor extension that checks the spelling of comments, strings, and plain text as you type or interactively with tool windows.
https://GitHub.com/EWSoftware/VSSpellChecker

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.
