### ISSUE TITLE
Coloring is incorrect for razor view pages

### ISSUE THREAD

**Issue by Mikaka27** [tomasr/viasfora#181]
Hi, I've noticed that colorization doesn't work properly for razor html pages.
See screenshot:
![viasfora](https://cloud.githubusercontent.com/assets/9214100/22399623/d184f8e2-e5a0-11e6-8f3d-a8a16a3352b8.PNG)

You can see that is conflicts both with normal html tag, and also with razor tag helpers (the ones with darker color, like <a asp-area="", asp-contro....).
Only closing tags are colored.

Edit:
Looking at the options it seems there are only closing tag coloring settings in Viasfora options.
Is this the correct behavior??
Please clarify and then we can close this if this is correct.

**Comment by tomasr** [comment]
Can you clarify what is the wrong part?

Are you referring to the closing HTML tags being rendered in another color? If so, this is not a bug; that's intentional; one of my favorite features in Vim color schemes.

You can already disable it if you don't want it by turning off the `Highlight Closing XML Tags` option in Tools -> Options -> Viasfora -> XML Editor.

Cheers!

**Comment by Mikaka27** [comment]
Hi,
I'm sorry I though it was supposed to highlight opening tags too.
But your solution actually makes sense, thanks for your response.

I'm closing it.
