### ISSUE TITLE
GetCurFile not implemented

### ISSUE THREAD

**Issue by jnyrup** [tomasr/viasfora#216]
After upgrading to VS2017 15.3 on every start VS reports:
> An exception has been encountered. This may be caused by an extension.

When inspected the log file, the only entry that is marked as an error is:
```
System.InvalidOperationException: GetCurFile returned 0x80004001&#x000D;&#x000A;  
Winterdom.Viasfora.TextEditor.CheckError(Int32 hr, String operation)&#x000D;&#x000A;  
Winterdom.Viasfora.TextEditor.GetFileName(ITextBuffer buffer)&#x000D;&#x000A;  
Winterdom.Viasfora.Outlining.UserOutliningManager.LoadRegions(ITextBuffer buffer)&#x000D;&#x000A;  
Winterdom.Viasfora.Outlining.UserOutliningManager.&lt;&gt;c__DisplayClass1_0.&lt;Get&gt;b__0()&#x000D;&#x000A;  
Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)&#x000D;&#x000A;  
Winterdom.Viasfora.Outlining.UserOutliningManager.Get(ITextBuffer buffer)&#x000D;&#x000A;  
Winterdom.Viasfora.Outlining.UserOutliningTaggerProvider.CreateTagger[T](ITextBuffer buffer)&#x000D;&#x000A;  
Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;  
Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

This seems related to #28

**Comment by tomasr** [comment]
That's an interesting one; thanks for reporting. I'm running 15.3 myself without seeing this error, so before digging deeper, can you tell me a couple of things?

* What other Visual Studio extensions do you have installed?
* What tool windows do you keep open by default? (or which ones are opened when you launch a new VS instance?)

Basically what I'm thinking is that since the error is happening on startup, there must be a tool window instantiating an editor window that has some particular behavior.

That said, I'm adding some error checking to handle this and let's see how it goes.

**Comment by tomasr** [comment]
Can you check the latest build from AppVeyor coming up in a few minutes and let me know how it works?

**Comment by jnyrup** [comment]
I tried disabling all extensions I've downloaded and the error went away.
I then enabled Viasfora and it re-appeared.
It only appeared when having the C# Interactive window open on startup.
Your build seemed to fix the problem.

**Comment by lkytal** [comment]
Same here.

**Comment by tomasr** [comment]
Fixed is deployed on the marketplace.
