### ISSUE TITLE
Convert to use AsyncPackage with background load

### ISSUE THREAD

**Issue by madskristensen** [tomasr/viasfora#236]
See more here https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background

**Comment by tomasr** [comment]
@madskristensen Do you have any data on Viasfora causing bad performance at load? (or anywhere else, for that matter) I'd be happy to take a look and see what can be improved.

Adding Async package support is unlikely to happen in the near term until I drop support for VS2012 and VS2013, which still make up about 14-15% of my users.

Another alternative that would likely have the same close result, though, would be making the load a lot simpler. Most of the stuff there could probably happen somewhere else on demand, except for the command menus initialization. Is there another way to do that which does not require messing with the package load?

**Comment by madskristensen** [comment]
Damn, I didn't see the support for VS2012/2013. If I saw that I wouldn't have opened this bug. Feel free to close it.

No, I have no data on slow perf. I was just going through the top extensions and opened bug on any extension that uses `ProvideAutoload` with a synchronous Package class if they supported VS2015+ only. In the future, sync package load will show the yellow bar

**Comment by tomasr** [comment]
I looked at the `AsyncPackage` implementation, and didn't seem to be a way to do that without dropping support for VS2012.

I did, however, manage to mostly refactor the code with only minor loss of functionality so that `[ProvideAutoLoad]` is no longer needed.

Closing this for now, but if you thing there's anything else I can/need do to ensure a good experience for users and continue supporting the VS rules, let me know.
